import './layout.scss'
import { Inter } from 'next/font/google'



export const metadata = {
  title: 'Portfolio',
  description: 'Generated by Saucedo Garcia',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="body">{children}</body>
    </html>
  )
}
