import './layout.scss'
import { Roboto } from 'next/font/google'


const roboto = Roboto({
  weight: ['300', '400', '500', '700', '900'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
})

export const metadata = {
  title: 'Portfolio',
  description: 'Generated by Saucedo Garcia',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} body`}>{children}</body>
    </html>
  )
}
